DATABASE = './hiddenlinks.db'
DEBUG = True
SECRET_KEY = "hairyballsack"
SOCKS_PORT = 9050
CONTROL_PORT = 9051
TOR_RESET_TIMER = 5
PHANTOM_PATH = ['./phantomjs']  # list of custom phantomjs binaries
MAX_BATCH_SIZE = 20000
MAX_THREAD_NUM = 8
